# Generated by Django 4.0.3 on 2022-04-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_course_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.staff'),
        ),
    ]
